import "./projects.css";
import Aurora from "../components/AuroraBG/Aurora.jsx";
import NavBar from "../components/NavBar/NavBar";
import Image from "next/image";
import Footer from "../components/Footer/Footer";

export default function Projects() {
  return (
    <div className="ProjectsContainer">
      <div className="BGContainer">
        <Aurora
          colorStops={["#22223C", "#0044ff", "#22223C"]}
          blend={1}
          amplitude={0.9}
          speed={0.8}
        />
      </div>
      <div className="ProjectsContent">
        <div className="NavBarWrapper">
          <NavBar />
        </div>
        <div className="ProjectsGallery">
          <Image
            className="GalleryImageUltraWide"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage45.png"
          />
          <Image
            className="GalleryImageUltraWide"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage46.png"
          />
          <Image
            className="GalleryImageUltraWide"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage47.png"
          />
          <Image
            className="GalleryImageUltraWide"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage48.png"
          />
          <Image
            className="GalleryImageUltraWide"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage49.png"
          />
          <Image
            className="GalleryImageUltraWide"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage50.png"
          />
          <Image
            className="GalleryImageUltraWide"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage03.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage01.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage02.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage10.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage11.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage12.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage13.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage15.png"
          />

          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage18.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage19.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage20.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage21.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage22.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage23.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage24.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage25.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage26.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage27.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage30.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage31.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage32.png"
          />

          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage34.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage35.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage36.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage37.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage38.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage39.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage40.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage41.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage42.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage43.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage44.png"
          />

          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage51.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage52.png"
          />
          <Image
            className="GalleryImageLandscape"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage53.png"
          />
          <Image
            className="GalleryImageChunky"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage04.png"
          />
          <Image
            className="GalleryImageChunky"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage05.png"
          />
          <Image
            className="GalleryImageChunky"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage06.png"
          />
          <Image
            className="GalleryImageChunky"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage07.png"
          />
          <Image
            className="GalleryImageChunky"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage09.png"
          />
          <Image
            className="GalleryImageChunky"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage17.png"
          />
          <Image
            className="GalleryImageChunky"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage29.png"
          />
          <Image
            className="GalleryImageChunkier"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage55.png"
          />
          <Image
            className="GalleryImageChunkier"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage14.png"
          />
          <Image
            className="GalleryImagePoster"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage28.png"
          />
          <Image
            className="GalleryImagePoster"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage33.png"
          />
          <Image
            className="GalleryImagePoster"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage16.png"
          />
          <Image
            className="GalleryImagePoster"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage08.png"
          />
          <Image
            className="GalleryImagePoster"
            width={1000}
            height={1000}
            alt=""
            src="/Images/GalleryImages/GalleryImage54.png"
          />
        </div>
        <Footer />
      </div>
    </div>
  );
}
